### ISSUE TITLE
Feature request: replace accents 

### ISSUE THREAD

**Issue by yurigoytacaz** [jielimanyili/sublime_string2_lower_hyphen#1]
It would be awesome if the plugin could also replace 'ã' to 'a', without the accent.
How about that? (=

**Comment by jielimanyili** [comment]
Thanks for finding this useful to some degree. Let me try to add this.
Jie

**Comment by jielimanyili** [comment]
Yuri,

I don’t know if you can receive this or not. I have updated this plugin. It should be able to replace any accents with their ascii text. Please test it out.
Thanks
Jie

**Comment by yurigoytacaz** [comment]
Hey, Jie! Nice to know you took time to code this. (=

I tried removing the package and installing it again, but now it doesnt seem to work at all. cmd+opt+L (lower L, I know) 
And that's another thing you should put in the readme, the font used in github is not clear about what letter is this: l 
)=

I tried quitting Sublime and reopening to test the new feature, but I don't know why is not working. 

![screen shot 2014-08-31 at 5 13 42 pm](https://cloud.githubusercontent.com/assets/682565/4103118/55de7bb6-314b-11e4-9d4f-7568df419edd.jpg)

**Comment by jielimanyili** [comment]
Hm. Let me fix it.
Jie

**Comment by jielimanyili** [comment]
Yuri,

Updated it again. Please test it again in an hour.
Jie

**Comment by yurigoytacaz** [comment]
Nice! worked perfectly. (=

**Comment by jielimanyili** [comment]
Thanks for testing! I will try to improve the docs.
Jie
